[package]
name = "nile"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
timer = "0.2.0"
tokio = { version = "1.43.0", features = ["time", "rt", "rt-multi-thread", "macros"] }
tokio-stream = "0.1.17"
